### ISSUE TITLE
Trigger word not being recognized

### ISSUE THREAD

**Issue by starscr3am77** [shivasiddharth/GassistPi#12]
Hi, I have everything installed and I verified the script runs on load by changing the startup wav and rebooting. Running google-assistant-demo works perfectly fine as well. The problem I am having is the trigger word is not being recognized. If I say hey google, the Fb.wav plays and I can ask the time. If I say "magic" (my trigger word) nothing happens. I added a subprocess to play the Tring.wav once the word is spoken (just copied the Pi-Close line) but when I say it, nothing happens. What's also odd, if I do say hey google, ask the time, every now and then your startup.wav will play again. This is a fresh installation with nothing else on it. I loaded the image then used your instructions. Any idea on why the trigger word isn't working? Or is it that I have to say hey google first then the trigger word. Any help would be greatly appreciated!

**Comment by shivasiddharth** [comment]
Hello,
1. You have to say hey google and then the trigger word. I have made it intentionally like that to prevent GPIO controls or pi shutdown due to false positives.
2.  Whatever you say after hey google will be processed together. Meaning, if you say hey google, trigger lights on, it will be processed as "trigger lights on"and not as "trigger" seperately and "lights on" separately. So there is no point in adding an audio feedback separately for the trigger. By the time tring finishes playing, the subsequent audio will start. It will be awful to the ears.
3. Regarding, startup playing in between, if you hit an error, the google assistant will re-start.
