### ISSUE TITLE
Failed building wheel for grpcio

### ISSUE THREAD

**Issue by paolorotolo** [shivasiddharth/GassistPi#143]
Log output:

```bash
Building wheels for collected packages: grpcio
Running setup.py bdist_wheel for grpcio ... error
Complete output from command /home/pi/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1elj70wp/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp1ry607i3pip-wheel- --python-tag cp35:
Found cython-generated files...
usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: -c --help [cmd1 cmd2 ...]
or: -c --help-commands
or: -c cmd --help

error: invalid command 'bdist_wheel'

----------------------------------------
Failed building wheel for grpcio
Running setup.py clean for grpcio
Failed to build grpcio
```

**Comment by vinnyJager** [comment]
You could try installing wheel. `pip install wheel
` after I did that it worked, took some time though

**Comment by RandallShanePhD** [comment]
This issue is back with Ubuntu 19.04 using python 3.7.3 and the pip installer.  Apologies for the length of the debug message here.  I cut out the part it did build else its war & peace!  Thx

`  ./src/core/lib/iomgr/ev_posix.h:46:16: warning: type ‘struct grpc_event_engine_vtable’ violates the C++ One Definition Rule [-Wodr]
   typedef struct grpc_event_engine_vtable {
                  ^
  ./src/core/lib/iomgr/ev_posix.h:46:16: note: a different type is defined in another translation unit
   typedef struct grpc_event_engine_vtable {
                  ^
  ./src/core/lib/iomgr/ev_posix.h:51:65: note: the first difference of corresponding definitions is field ‘fd_create’
     grpc_fd* (*fd_create)(int fd, const char* name, bool track_err);
                                                                   ^
  ./src/core/lib/iomgr/ev_posix.h:51:65: note: a field of same name but different type is defined in another translation unit
     grpc_fd* (*fd_create)(int fd, const char* name, bool track_err);
                                                                   ^
  src/core/lib/iomgr/ev_epoll1_linux.cc:141:8: warning: type ‘struct grpc_fd’ violates the C++ One Definition Rule [-Wodr]
   struct grpc_fd {
          ^
  src/core/lib/iomgr/ev_epollex_linux.cc:164:8: note: a different type is defined in another translation unit
   struct grpc_fd {
          ^
  src/core/lib/iomgr/ev_epoll1_linux.cc:144:58: note: the first difference of corresponding definitions is field ‘read_closure’
     grpc_core::ManualConstructor<grpc_core::LockfreeEvent> read_closure;
                                                            ^
  src/core/lib/iomgr/ev_epollex_linux.cc:237:19: note: a field with different name is defined in another translation unit
     gpr_atm refst = 1;
                     ^
  src/core/lib/iomgr/ev_epoll1_linux.cc:177:8: warning: type ‘struct grpc_pollset_worker’ violates the C++ One Definition Rule [-Wodr]
   struct grpc_pollset_worker {
          ^
  src/core/lib/iomgr/ev_epollex_linux.cc:273:8: note: a different type is defined in another translation unit
   struct grpc_pollset_worker {
          ^
  src/core/lib/iomgr/ev_epoll1_linux.cc:178:14: note: the first difference of corresponding definitions is field ‘state’
     kick_state state;
                ^
  src/core/lib/iomgr/ev_epollex_linux.cc:274:8: note: a field with different name is defined in another translation unit
     bool kicked;
          ^
  src/core/lib/iomgr/ev_epoll1_linux.cc:205:8: warning: type ‘struct grpc_pollset’ violates the C++ One Definition Rule [-Wodr]
   struct grpc_pollset {
          ^
  src/core/lib/iomgr/ev_epollex_linux.cc:287:8: note: a different type is defined in another translation unit
   struct grpc_pollset {
          ^
  src/core/lib/iomgr/ev_epoll1_linux.cc:207:25: note: the first difference of corresponding definitions is field ‘neighborhood’
     pollset_neighborhood* neighborhood;
                           ^
  src/core/lib/iomgr/ev_epollex_linux.cc:289:11: note: a field with different name is defined in another translation unit
     gpr_atm worker_count;
             ^
  src/core/lib/iomgr/ev_epoll1_linux.cc:230:8: warning: type ‘struct grpc_pollset_set’ violates the C++ One Definition Rule [-Wodr]
   struct grpc_pollset_set {
          ^
  src/core/lib/iomgr/ev_epollex_linux.cc:303:8: note: a different type is defined in another translation unit
   struct grpc_pollset_set {
          ^
  src/core/lib/iomgr/ev_epoll1_linux.cc:231:8: note: the first difference of corresponding definitions is field ‘unused’
     char unused;
          ^
  src/core/lib/iomgr/ev_epollex_linux.cc:304:23: note: a field with different name is defined in another translation unit
     grpc_core::RefCount refs;
                         ^
  src/core/lib/iomgr/ev_epoll1_linux.cc:488:45: warning: type ‘worker_remove_result’ violates the C++ One Definition Rule [-Wodr]
   typedef enum { EMPTIED, NEW_ROOT, REMOVED } worker_remove_result;
                                               ^
  src/core/lib/iomgr/ev_epollex_linux.cc:984:57: note: an enum with different value name is defined in another translation unit
   typedef enum { WRR_NEW_ROOT, WRR_EMPTIED, WRR_REMOVED } worker_remove_result;
                                                           ^
  src/core/lib/iomgr/ev_epoll1_linux.cc:135:8: warning: type ‘struct grpc_fork_fd_list’ violates the C++ One Definition Rule [-Wodr]
   struct grpc_fork_fd_list {
          ^
  src/core/lib/iomgr/ev_poll_posix.cc:65:8: note: a different type is defined in another translation unit
   struct grpc_fork_fd_list {
          ^
  src/core/lib/iomgr/ev_epoll1_linux.cc:136:12: note: the first difference of corresponding definitions is field ‘fd’
     grpc_fd* fd;
              ^
  src/core/lib/iomgr/ev_poll_posix.cc:68:12: note: a field of same name but different type is defined in another translation unit
     grpc_fd* fd;
              ^
  ./src/core/lib/iomgr/ev_posix.h:44:24: note: type ‘struct grpc_fd’ should match type ‘struct grpc_fd’
   typedef struct grpc_fd grpc_fd;
                          ^
  src/core/lib/iomgr/tcp_server_custom.cc:43:8: warning: type ‘struct grpc_tcp_listener’ violates the C++ One Definition Rule [-Wodr]
   struct grpc_tcp_listener {
          ^
  ./src/core/lib/iomgr/tcp_server_utils_posix.h:30:16: note: a different type is defined in another translation unit
   typedef struct grpc_tcp_listener {
                  ^
  src/core/lib/iomgr/tcp_server_custom.cc:44:20: note: the first difference of corresponding definitions is field ‘server’
     grpc_tcp_server* server;
                      ^
  ./src/core/lib/iomgr/tcp_server_utils_posix.h:31:7: note: a field with different name is defined in another translation unit
     int fd;
         ^
  src/core/lib/iomgr/tcp_server_custom.cc:56:8: warning: type ‘struct grpc_tcp_server’ violates the C++ One Definition Rule [-Wodr]
   struct grpc_tcp_server {
          ^
  ./src/core/lib/iomgr/tcp_server_utils_posix.h:52:8: note: a different type is defined in another translation unit
   struct grpc_tcp_server {
          ^
  src/core/lib/iomgr/tcp_server_custom.cc:60:22: note: the first difference of corresponding definitions is field ‘on_accept_cb’
     grpc_tcp_server_cb on_accept_cb;
                        ^
  ./src/core/lib/iomgr/tcp_server_utils_posix.h:55:22: note: a field of same name but different type is defined in another translation unit
     grpc_tcp_server_cb on_accept_cb;
                        ^
  third_party/zlib/gzlib.c:252:9: warning: type of ‘lseek’ does not match original declaration [-Wlto-type-mismatch]
           LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
           ^
  /usr/include/unistd.h:334:16: note: return value type mismatch
   extern __off_t lseek (int __fd, __off_t __offset, int __whence) __THROW;
                  ^
  /usr/include/unistd.h:334:16: note: type ‘__off_t’ should match type ‘int’
  /usr/include/unistd.h:334:16: note: ‘lseek’ was previously declared here
  /usr/include/unistd.h:334:16: note: code may be misoptimized unless -fno-strict-aliasing is used
  third_party/zlib/gzread.c:35:15: warning: type of ‘read’ does not match original declaration [-Wlto-type-mismatch]
           ret = read(state->fd, buf + *have, get);
                 ^
  /usr/include/x86_64-linux-gnu/bits/unistd.h:25:16: note: return value type mismatch
   extern ssize_t __REDIRECT (__read_alias, (int __fd, void *__buf,
                  ^
  /usr/include/x86_64-linux-gnu/bits/unistd.h:25:16: note: type ‘ssize_t’ should match type ‘int’
  /usr/include/x86_64-linux-gnu/bits/unistd.h:25:16: note: ‘__read_alias’ was previously declared here
  /usr/include/x86_64-linux-gnu/bits/unistd.h:25:16: note: code may be misoptimized unless -fno-strict-aliasing is used
  third_party/zlib/gzwrite.c:89:20: warning: type of ‘write’ does not match original declaration [-Wlto-type-mismatch]
               writ = write(state->fd, strm->next_in, put);
                      ^
  /usr/include/unistd.h:366:16: note: return value type mismatch
   extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur;
                  ^
  /usr/include/unistd.h:366:16: note: type ‘ssize_t’ should match type ‘int’
  /usr/include/unistd.h:366:16: note: ‘write’ was previously declared here
  /usr/include/unistd.h:366:16: note: code may be misoptimized unless -fno-strict-aliasing is used
  /usr/bin/ld: /tmp/ccAd7bVr.ltrans1.ltrans.o: in function `upb_arena_doalloc.lto_priv.659':
  /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34: undefined reference to `__wrap_memcpy'
  /usr/bin/ld: /tmp/ccAd7bVr.ltrans1.ltrans.o: in function `upb_msg_addunknown':
  /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34: undefined reference to `__wrap_memcpy'
  /usr/bin/ld: /tmp/ccAd7bVr.ltrans1.ltrans.o: in function `upb_array_add':
  /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34: undefined reference to `__wrap_memcpy'
  /usr/bin/ld: /tmp/ccAd7bVr.ltrans1.ltrans.o: in function `flush_pending':
  /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34: undefined reference to `__wrap_memcpy'
  /usr/bin/ld: /tmp/ccAd7bVr.ltrans1.ltrans.o: in function `upb_put_bytes':
  /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34: undefined reference to `__wrap_memcpy'
  /usr/bin/ld: /tmp/ccAd7bVr.ltrans1.ltrans.o:/usr/include/x86_64-linux-gnu/bits/string_fortified.h:34: more undefined references to `__wrap_memcpy' follow
  collect2: error: ld returned 1 exit status
  Traceback (most recent call last):
    File "/usr/lib/python3.7/distutils/unixccompiler.py", line 215, in link
      self.spawn(linker + ld_args)
    File "/tmp/pip-install-ram15zel/grpcio/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
      _classic_spawn(self, command)
    File "/usr/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
      spawn(cmd, dry_run=self.dry_run)
    File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
      _spawn_posix(cmd, search_path, dry_run=dry_run)
    File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
      % (cmd, exit_status))
  distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-g++' failed with exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/tmp/pip-install-ram15zel/grpcio/src/python/grpcio/commands.py", line 262, in build_extensions
      build_ext.build_ext.build_extensions(self)
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 199, in build_extension
      _build_ext.build_extension(self, ext)
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 559, in build_extension
      target_lang=language)
    File "/usr/lib/python3.7/distutils/ccompiler.py", line 717, in link_shared_object
      extra_preargs, extra_postargs, build_temp, target_lang)
    File "/usr/lib/python3.7/distutils/unixccompiler.py", line 217, in link
      raise LinkError(msg)
  distutils.errors.LinkError: command 'x86_64-linux-gnu-g++' failed with exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-ram15zel/grpcio/setup.py", line 400, in <module>
      cmdclass=COMMAND_CLASS,
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-ram15zel/grpcio/src/python/grpcio/commands.py", line 265, in build_extensions
      support.diagnose_build_ext_error(self, error, formatted_exception)
    File "/tmp/pip-install-ram15zel/grpcio/src/python/grpcio/support.py", line 109, in diagnose_build_ext_error
      "backtrace).\n\n{}".format(formatted))
  commands.CommandError:

  We could not diagnose your build failure. If you are unable to proceed, please file an issue at http://www.github.com/grpc/grpc with `[Python install]` in the title; please attach the whole log (including everything that may have appeared above the Python backtrace).

  Traceback (most recent call last):
    File "/usr/lib/python3.7/distutils/unixccompiler.py", line 215, in link
      self.spawn(linker + ld_args)
    File "/tmp/pip-install-ram15zel/grpcio/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
      _classic_spawn(self, command)
    File "/usr/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
      spawn(cmd, dry_run=self.dry_run)
    File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
      _spawn_posix(cmd, search_path, dry_run=dry_run)
    File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
      % (cmd, exit_status))
  distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-g++' failed with exit status 1

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/tmp/pip-install-ram15zel/grpcio/src/python/grpcio/commands.py", line 262, in build_extensions
      build_ext.build_ext.build_extensions(self)
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 199, in build_extension
      _build_ext.build_extension(self, ext)
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 559, in build_extension
      target_lang=language)
    File "/usr/lib/python3.7/distutils/ccompiler.py", line 717, in link_shared_object
      extra_preargs, extra_postargs, build_temp, target_lang)
    File "/usr/lib/python3.7/distutils/unixccompiler.py", line 217, in link
      raise LinkError(msg)
  distutils.errors.LinkError: command 'x86_64-linux-gnu-g++' failed with exit status 1


  ----------------------------------------
  Failed building wheel for grpcio
  Running setup.py clean for grpcio
Failed to build grpcio`

**Comment by shivasiddharth** [comment]
@RandallShanePhD , For Ubuntu I have tested it only till the Bionic version. I have clearly mentioned that in the README. https://github.com/shivasiddharth/GassistPi#only-oses-suported-are
