### ISSUE TITLE
GassistPi Restarting

### ISSUE THREAD

**Issue by nesperida911** [shivasiddharth/GassistPi#26]
GassistPi is restarting when i ask something and it takes time to respond but instead to respond to my question it restarted the service. i am using raspberry pi 3 model b

**Comment by shivasiddharth** [comment]
I have set the service to restart if the assistant encountered some kind of error. The restart on wakeword detection could be due to reaching the limit of wakeword usages or due to handshake errors. I would suggest you to stop the service and manually run the main.py within the environment. That will display the error that you are encountering.
