### ISSUE TITLE
RPi Zero w only startup music---not working otherwise

### ISSUE THREAD

**Issue by GunmanTech** [shivasiddharth/GassistPi#299]
Hey, I just tried to install the GassistPi on my raspberry pi zero accompanied by a generic usb soundcard.. Everything went as expected. But since the authentication process ended, It just randomly sounds the welcome tone and "hi"--- nothing else happens. Even after several restarts, the same thing persists. Ocassionally, the led on the usb soundcard blinks, but nothing happens even though i scream "ok, Google" at it. Even as I am typing this, the same thing is going on repeatedly(at least 6 times till now). Please help me out.

**Comment by shivasiddharth** [comment]
Even if you scream on top of your voice, it will not pickup the "ok google" hotword, because it is not meant for that. "Ok Goolge" hotword is compatible only with Pi 3, Pi 2 and other Armv7 boards. For more info on compatablity please go through this (page)[https://developers.google.com/assistant/sdk/overview#features]

That is why i have broken instructions separately for Pi 3 and Pi zero.
